// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sunrise.Config;

namespace sunrise.Migrations
{
    [DbContext(typeof(DaoContext))]
    [Migration("20200420082710_CityInitialData")]
    partial class CityInitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {

        }
    }
}
